name: Bug Report (ring-client-api)
description: Report a bug in ring-client-api
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        If this is a Live Stream issue please go back and use the Live Streaming issue template.
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
          required: true
  - type: textarea
    attributes:
      label: Describe The Bug
      placeholder: A clear and concise description of the problem...
    validations:
      required: true
  - type: textarea
    attributes:
      label: To Reproduce
      placeholder: Steps to reproduce the behavior. - Create an `ApiClient` - Attempt to ...  - See error
    validations:
      required: false
  - type: textarea
    attributes:
      label: Expected behavior
      placeholder: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: Logs
    attributes:
      label: Relevant log output
      placeholder: If applicable, add log output to help explain your problem.
      render: shell
    validations:
      required: false
  - type: textarea
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
      placeholder: You can attach images by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional context
      placeholder: Add any other context about the problem here.
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        Environment
  - type: input
    attributes:
      label: OS
      placeholder: Rasbian, macOS, Windows, Linux
    validations:
      required: true
  - type: input
    attributes:
      label: Node.js Version
      placeholder: v14.17.6
    validations:
      required: true
  - type: input
    attributes:
      label: NPM Version
      placeholder: v7.22.0
    validations:
      required: true
  - type: input
    attributes:
      label: ring-client-api
      placeholder: v6.0.3
    validations:
      required: true
  - type: input
    attributes:
      label: Operating System
      placeholder: Raspbian / Ubuntu / Debian / Windows / macOS / Docker
    validations:
      required: true
