
blank_issues_enabled: false
contact_links:
  - name: Homebridge Discord Channel for Ring
    url: https://discord.gg/CXryEzNC
    about: For general questions and discussion about homebridge-ring
  - name: Homebridge Reddit
    url: https://www.reddit.com/r/homebridge/
    about: The fastest way to get help and advice from the homebridge community
