name: Feature Request
description: Suggest an idea for this project
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: Description
      placeholder: A clear and concise description of the problem or missing capability...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposed solution
      description: Describe the solution you'd like to see implmented
    validations:
      required: false
  - type: textarea
    attributes:
      label: Alternatives
      description: Have you considered any alternative solutions or workarounds?
    validations:
      required: false
  - type: textarea
    attributes:
      label: Device data
      description: If you are requesting a new device or feature that uses data from a device, please follow the instructions in https://github.com/dgreif/ring/wiki/Data-Discovery and include the output here
      placeholder: Place device data output here
    validations:
      required: false
