name: Live Streaming Issue
description: Having trouble with Live Streaming
title: "[Streaming]: "
labels: [live-streaming]
body:
  - type: markdown
    attributes:
      value: |
        Please see the [Camera Troubleshooting Docs](https://github.com/dgreif/ring/wiki/Camera-Troubleshooting) first, as it contains my best advice for streaming issues.  Unless you have a suggestion of how your streaming issue can be fixed, I likely can't help you beyond what is in that wiki article.  
  - type: textarea
    id: contact
    attributes:
      label: Streaming Issue
      description: Describe the problem you are having with live streams
      placeholder: Solution
    validations:
      required: false
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How do you think this issue could be fixed?  If you cannot provide an answer here, I likely cannot help you.
      placeholder: Solution
    validations:
      required: true
  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: Where are you live streaming
      options:
        - Homebridge
        - HOOBS
        - Other (ring-client-api)
    validations:
      required: true
  - type: dropdown
    id: OS
    attributes:
      label: What operating system are you on?
      options:
        - Linux
        - Mac
        - Windows
        - Other
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: double-check
    attributes:
      label: Verification
      description: By submitting this issue, you agree that you have already consulted the [Camera Troubleshooting Docs](https://github.com/dgreif/ring/wiki/Camera-Troubleshooting) and have something useful to contribute.
      options:
        - label: I swear this is worth your time!
          required: true
